import test from 'node:test';
import assert from 'node:assert/strict';
import {handle} from '../worker/inquiry.mjs';
const valid={name:'Test Person',email:'test@example.com',service:'motorized-shades',rooms:'Bedroom privacy',projectStage:'retrofit',website:'','cf-turnstile-response':'test-token'};
const env={ALLOWED_ORIGINS:'https://davg.ai',TURNSTILE_SECRET_KEY:'test-secret',HUBSPOT_PORTAL_ID:'123',HUBSPOT_FORM_GUID:'00000000-0000-0000-0000-000000000000',HUBSPOT_FIELD_MAP:JSON.stringify({name:'firstname',email:'email',rooms:'message'}),RATE_LIMITER:{limit:async()=>({success:true})}};
const request=(data=valid,headers={},method='POST')=>new Request('https://inquiry.example.com/api/inquiry',{method,headers:{Origin:'https://davg.ai','Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1',...headers},...(method==='POST'?{body:JSON.stringify(data)}:{})});
const never=()=>{throw new Error('External delivery must not run');};
test('rejects unapproved origins before external delivery',async()=>assert.equal((await handle(request(valid,{Origin:'https://other.example'}),env,never)).status,403));
test('does not pretend to send without configuration',async()=>assert.equal((await handle(request(),{ALLOWED_ORIGINS:env.ALLOWED_ORIGINS},never)).status,503));
test('validates required fields before delivery',async()=>assert.equal((await handle(request({...valid,email:'bad'}),env,never)).status,400));
test('rejects a populated honeypot',async()=>assert.equal((await handle(request({...valid,website:'spam'}),env,never)).status,400));
test('requires a Turnstile token',async()=>assert.equal((await handle(request({...valid,'cf-turnstile-response':''}),env,never)).status,400));
test('limits request bodies even without Content-Length',async()=>assert.equal((await handle(request({...valid,rooms:'a'.repeat(9000)}),env,never)).status,413));
test('enforces rate limiting',async()=>assert.equal((await handle(request(),{...env,RATE_LIMITER:{limit:async()=>({success:false})}},never)).status,429));
test('rejects failed Turnstile validation',async()=>assert.equal((await handle(request(),env,async()=>Response.json({success:false}))).status,400));
test('rejects mismatched verification hostname',async()=>assert.equal((await handle(request(),env,async()=>Response.json({success:true,action:'inquiry',hostname:'other.example'}))).status,400));
test('does not report success when HubSpot fails',async()=>{let n=0;const response=await handle(request(),env,async()=>++n===1?Response.json({success:true,action:'inquiry',hostname:'davg.ai'}):new Response('',{status:500}));assert.equal(response.status,502);});
test('accepts only after verified delivery and never forwards the token',async()=>{let n=0;const response=await handle(request(),env,async(url,options)=>{if(++n===1)return Response.json({success:true,action:'inquiry',hostname:'davg.ai'});assert.match(url,/api.hsforms.com/);assert.doesNotMatch(options.body,/test-token|test-secret/);assert.equal(JSON.parse(options.body).fields.find(f=>f.name==='email').value,'test@example.com');return new Response('',{status:200});});assert.equal(response.status,200);assert.deepEqual(await response.json(),{status:'accepted'});assert.equal(n,2);});
test('answers a permitted preflight without delivery',async()=>assert.equal((await handle(request(undefined,{},'OPTIONS'),env,never)).status,204));
